version: '3.9'
services:
  cloud9:
    build: .
    restart: always
    ports:
      - '8081:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/cloud9'
      - SPRING_DATASOURCE_USERNAME=cloud9
      - SPRING_DATASOURCE_PASSWORD=cloud9
    depends_on:
      - flyway
  flyway:
    image: 'flyway/flyway:latest-alpine'
    command: '-url=jdbc:postgresql://postgres_db:5432/cloud9 -user=cloud9 -password=cloud9 -connectRetries=6 info migrate info'
    volumes:
      - './src/main/resources/db/migration:/flyway/sql'
    depends_on:
      - postgres_db
  postgres_db:
    image: 'postgres:latest'
    restart: always
    volumes:
      - '../db/cloud9-data:/var/lib/postgresql/data'
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: cloud9
      POSTGRES_PASSWORD: cloud9
      POSTGRES_DB: cloud9
