version: "3.7"
services:
  cloud9:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
      image: "postgres"
      restart: always
      volumes:
        - /private/var/lib/postgresql:/var/lib/docker/volumes/cloud9_db
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: cloud9