version: "3.9"
services:
  cloud9:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - flyway
  flyway:
    image: flyway/flyway:latest-alpine
    command: -url=jdbc:postgresql://postgres_db:5432/cloud9 -user=postgres -password=postgres -connectRetries=6 info migrate info
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    restart: always
    volumes:
      - ./src/main/resources/db/cloud9-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud9