import Head from 'next/head'

export default function Home({ customers }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <main>
        <div>
          <ul>
            <h2>Customer Emails: </h2>
            {customers.map((customer) => {
              return <>
                <p>First Name:{customer.full_name}</p>
                <p>First Name:{customer.email}</p>
                <p>First Name:{customer.city}</p>
                <p>First Name:{customer.address.streetName}</p>

              </>
            })}
          </ul>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {

  const res = await fetch('http://localhost:8080/api/customers/list/customers?_limit=2')
  const customers = await res.json()
  console.log(`Customers: ${customers}`)
  return {
    props: {
      customers,
    },
  }
}